### ISSUE TITLE
Circuit diagram

### ISSUE THREAD

**Issue by 3100jisa** [ChangboBro/ST7567-micropython-framebuff#1]
Can you provide connection diagram between Pico and LCD?

I have similar LCD with pins GND, VCC, SCL, SDA, DC, RST, CS, BL, CS-F, OUT being sold as ST7567A SPI LCD display. I want to give it a try.

**Comment by ChangboBro** [comment]
You have many options to connect your screen and your Ras-Pi-pico, its not fixed.
In the demo file, the spi and lcd object is defined as:
``` python3
spi = SPI(0,baudrate=200_000, polarity=1, phase=1, sck=Pin(2), mosi=Pin(3),miso=Pin(16))#under 20Mhz is OK
lcd=ST7567(spi,a0=Pin(1),cs=Pin(5),rst=Pin(4),elecvolt=0x32,regratio=0x05,invX=False,invY=True,invdisp=0)
``` 
So, you should connect them as this:
pins of Ras-Pi-pico|pins of your screen
|---|---|
2   |sck(scl)
3   |mosi(sda)
16(optional)  |miso(out?)
1   |a0(dc)
5   |cs
4   |rst

This program did't implement functions that need miso, so actually you don't need to connect that.
BL pin controls the backlight of your screen.
VCC/GND are power pins, this screen uses 3.3v for power.
You can change the pin for your circuit, as long as you change your code too. Note the SPI pins should conform to the constrain of Raspberry Pi Pico Pinout.
